### ISSUE TITLE
Unexpected behavior in Webstorm on Mac OS Siera.

### ISSUE THREAD

**Issue by ViktorSoroka** [azz/pretty-quick#16]
I am using the latest version of the **Webstorm**. 

1) After commit (it is done via IDE (cmd + K) shorthand), the files seems to be added to the commit with fixes but in the **Webstorm** they are still in the staged mode after the commit was done (but there is no changes in that files if looking to the diff). After trying to commit that files again the rules applies for them again (i.e the second empty line at the end of the file despite there is already one present).

2) after the file was already prettied and for some reason some formatting changes were made in that file and after the commit command was made only for that file - the prettier task run for that file and creates an empty commit without any changes (which makes sense but it would be better to prevent that commit instead).

Probably this is a result of the known issue https://github.com/okonet/lint-staged/issues/151

**Comment by azz** [comment]
This is really unfortunate. Sounds like since webstorm isn't actually staging the files that this tool will not work in staged mode. I'm not sure it is possible to fix in this library so I'm going to close the issue and recommend tracking https://youtrack.jetbrains.com/issue/IDEA-135454.

If anyone has any ideas how to fix this here please comment and we can re-open this.
